export type AuthStackParamList = {
  Login: undefined;
  Signup: undefined;
  Home: undefined;
  Journal: undefined;
  CreateJournalEntry: undefined;
  Saint: undefined;
  CreateSaint: undefined;
  Profile: undefined;
  Landing: undefined;
  EmailAndPassword: undefined;
  AdminPanel: undefined;
  Prayer: undefined;
  Rosary: undefined;
  PrayerList: undefined;
  GoogleLogin: undefined;
  CalendarModal: undefined;
  Settings: undefined;
  "Privacy Policy": undefined;
  "Terms of Service": undefined;
  About: undefined;
  Feedback: undefined;
  AdminAllUsersScreen: undefined;
  AdminFeedbackScreen: undefined;
  AdminUserOverview: { userId: string };
  Licenses: undefined;
};
